name: macOS arm64

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: 📦 Build
        run: cd SPMDepsGraph && swift build
      - name: Author Fake Modification
        run: echo "// A random file modification to check depsgraph change detection." >> SPMDepsGraph/Sources/SPMDepsApp/SPMDepsApp.swift
      - name: 📦 Build Again (Detect Dependency Graph Changes)
        run: cd SPMDepsGraph && swift build
